/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#5B4CFF",
          foreground: "#FFFFFF",
          light: "#7C6DFF",
          50: "#F3F1FF",
          100: "#E8E5FF",
          200: "#D3CCFF",
          300: "#B7ADFF",
          400: "#7C6DFF",
          500: "#5B4CFF",
          600: "#4538E8",
          700: "#3328B8",
          800: "#261E88",
          900: "#171252",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          gray: {
            50: "#FBFBFD",
            100: "#F5F7FB",
            200: "#E8ECF4",
            300: "#D7DEEA",
            400: "#AEB8C8",
            500: "#697586",
            600: "#525F70",
            700: "#364152",
            800: "#202938",
            900: "#121826",
          }
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        navy: {
          50: "#F6F8FC",
          100: "#EAF0F8",
          200: "#CAD6E5",
          300: "#9FB0C6",
          400: "#7487A0",
          500: "#53657D",
          600: "#3D4B61",
          700: "#263247",
          800: "#172033",
          900: "#0E1320",
        },
        green: {
          50: "#E6FFF3",
          100: "#CCFFE7",
          200: "#99FFCF",
          300: "#66FFB7",
          400: "#33FF9F",
          500: "#01B574",
          600: "#01915D",
          700: "#016D46",
          800: "#00482E",
          900: "#002417",
        },
        orange: {
          50: "#FFF8E6",
          100: "#FFEFCC",
          200: "#FFE099",
          300: "#FFD066",
          400: "#FFC133",
          500: "#FFB547",
          600: "#E6A340",
          700: "#B37F32",
          800: "#805C24",
          900: "#4D3816",
        },
        red: {
          50: "#FDE8E8",
          100: "#FBD0D0",
          200: "#F7A1A1",
          300: "#F37272",
          400: "#EF4444",
          500: "#EE5D50",
          600: "#D45246",
          700: "#A43F36",
          800: "#752D27",
          900: "#451B17",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        "2xl": "18px",
        "3xl": "28px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 18px 45px rgba(34, 42, 66, 0.06)",
        "card-hover": "0 22px 55px rgba(34, 42, 66, 0.11)",
        navbar: "0 16px 45px rgba(34, 42, 66, 0.08)",
      },
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
      },
      letterSpacing: {
        tighter: "0px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-urgency": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-urgency": "pulse-urgency 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
