import type { Trend, Notification, ContentItem } from '@/types';

export const mockTrends: Trend[] = [
  {
    id: '1',
    name: 'Botol Minum Kaca Viral',
    category: 'rumah-tangga',
    growth: 187,
    saturation: 28,
    phase: 'Growing',
    platform: 'TikTok Shop',
    timeDetected: '2 jam yang lalu',
    windowHours: 58,
    thumbnail: 'https://picsum.photos/seed/botol-minum/400/300',
    competitorCount: 12,
    avgPrice: 45000,
    reviewVelocity: 89,
    description: 'Botol minum kaca estetik dengan tutup bambu sedang viral di TikTok. Konten ASMR pengisian air dan infused water mendapat jutaan views.',
    recommendation: 'Aman masuk — peluang terbuka. Pertimbangkan stok minimal 30 pcs dengan modal Rp 750 ribu.',
  },
  {
    id: '2',
    name: 'Lampu Tidur 3D Moon',
    category: 'elektronik',
    growth: 312,
    saturation: 15,
    phase: 'Emerging',
    platform: 'TikTok Shop',
    timeDetected: '45 menit yang lalu',
    windowHours: 68,
    thumbnail: 'https://picsum.photos/seed/lampu-moon/400/300',
    competitorCount: 8,
    avgPrice: 125000,
    reviewVelocity: 156,
    description: 'Lampu tidur proyektor bulan 3D dengan 16 warna. Video unboxing dan review di TikTok mencapai 2.5M views dalam 12 jam.',
    recommendation: 'Aman masuk — window masih sangat terbuka. Stok 50 pcs dengan modal Rp 3 juta direkomendasikan.',
  },
  {
    id: '3',
    name: 'Tisu Basah Portable',
    category: 'kecantikan',
    growth: 52,
    saturation: 67,
    phase: 'Peak',
    platform: 'Shopee',
    timeDetected: '6 jam yang lalu',
    windowHours: 18,
    thumbnail: 'https://picsum.photos/seed/tisu-basah/400/300',
    competitorCount: 89,
    avgPrice: 15000,
    reviewVelocity: 234,
    description: 'Tisu basah mini dengan kemasan saku. Sudah melewati fase peak, kejenuhan tinggi dengan banyak kompetitor.',
    recommendation: 'Hindari saat ini — kejenuhan tinggi. Cari variasi produk atau tunggu tren berikutnya.',
  },
  {
    id: '4',
    name: 'Lampu Proyektor Aurora',
    category: 'elektronik',
    growth: 156,
    saturation: 35,
    phase: 'Growing',
    platform: 'TikTok Shop',
    timeDetected: '3 jam yang lalu',
    windowHours: 52,
    thumbnail: 'https://picsum.photos/seed/lampu-aurora/400/300',
    competitorCount: 22,
    avgPrice: 98000,
    reviewVelocity: 178,
    description: 'Lampu proyektor aurora dengan remote control. Tren penerus lampu LED strip yang mulai turun.',
    recommendation: 'Pertimbangkan ulang — pasar mulai ramai. Bedakan dengan bundling atau USP unik.',
  },
  {
    id: '5',
    name: 'Raket Nyamuk Elektrik USB',
    category: 'rumah-tangga',
    growth: -8,
    saturation: 78,
    phase: 'Decay',
    platform: 'Shopee',
    timeDetected: '2 hari yang lalu',
    windowHours: 6,
    thumbnail: 'https://picsum.photos/seed/raket-nyamuk/400/300',
    competitorCount: 145,
    avgPrice: 35000,
    reviewVelocity: 45,
    description: 'Raket nyamuk dengan charger USB. Sudah lewat fase peak, banyak kompetitor dengan harga murah.',
    recommendation: 'Hindari saat ini — kejenuhan tinggi. Window hampir tertutup.',
  },
  {
    id: '6',
    name: 'Earphone Wireless TWS',
    category: 'elektronik',
    growth: -16,
    saturation: 82,
    phase: 'Decay',
    platform: 'Shopee',
    timeDetected: '3 hari yang lalu',
    windowHours: 2,
    thumbnail: 'https://picsum.photos/seed/earphone-tws/400/300',
    competitorCount: 312,
    avgPrice: 65000,
    reviewVelocity: 23,
    description: 'Earphone TWS generik dengan banyak variasi. Kategori sangat jenuh, sulit bersaing tanpa brand.',
    recommendation: 'Hindari saat ini — kejenuhan sangat tinggi. Cari niche atau variasi premium.',
  },
  {
    id: '7',
    name: 'Tote Bag Kanvas Custom',
    category: 'fashion',
    growth: 142,
    saturation: 42,
    phase: 'Growing',
    platform: 'Instagram',
    timeDetected: '4 jam yang lalu',
    windowHours: 44,
    thumbnail: 'https://picsum.photos/seed/tote-bag/400/300',
    competitorCount: 38,
    avgPrice: 55000,
    reviewVelocity: 67,
    description: 'Tote bag kanvas dengan custom nama/quote. Populer di Instagram Reels sebagai gift idea.',
    recommendation: 'Aman masuk — peluang terbuka. Fokus pada custom design untuk diferensiasi.',
  },
  {
    id: '8',
    name: 'Minuman Kolagen Sachet',
    category: 'makanan',
    growth: 67,
    saturation: 55,
    phase: 'Peak',
    platform: 'TikTok Shop',
    timeDetected: '5 jam yang lalu',
    windowHours: 28,
    thumbnail: 'https://picsum.photos/seed/kolagen-sachet/400/300',
    competitorCount: 67,
    avgPrice: 25000,
    reviewVelocity: 198,
    description: 'Minuman kolagen instan dalam sachet. Viral di TikTok dengan konten "before after" kulit.',
    recommendation: 'Pertimbangkan ulang — pasar mulai ramai tapi masih ada window. Masuk cepat dengan bundling.',
  },
  {
    id: '9',
    name: 'Smartwatch Anak-anak',
    category: 'elektronik',
    growth: 134,
    saturation: 45,
    phase: 'Growing',
    platform: 'Shopee',
    timeDetected: '7 jam yang lalu',
    windowHours: 38,
    thumbnail: 'https://picsum.photos/seed/smartwatch-anak/400/300',
    competitorCount: 34,
    avgPrice: 175000,
    reviewVelocity: 89,
    description: 'Smartwatch dengan GPS tracking untuk anak. Naik menjelang musim liburan sekolah.',
    recommendation: 'Aman masuk — peluang terbuka. Target parents menjelang liburan.',
  },
  {
    id: '10',
    name: 'Serum Niacinamide 10%',
    category: 'kecantikan',
    growth: 168,
    saturation: 38,
    phase: 'Growing',
    platform: 'Instagram',
    timeDetected: '8 jam yang lalu',
    windowHours: 46,
    thumbnail: 'https://picsum.photos/seed/serum-niacinamide/400/300',
    competitorCount: 29,
    avgPrice: 38000,
    reviewVelocity: 134,
    description: 'Serum niacinamide 10% dengan packaging minimalis. Trending di beauty community Instagram.',
    recommendation: 'Aman masuk — peluang terbuka. Fokus pada review skincare routine.',
  },
  {
    id: '11',
    name: 'Sandal Slide Pria Premium',
    category: 'fashion',
    growth: 118,
    saturation: 52,
    phase: 'Growing',
    platform: 'Shopee',
    timeDetected: '10 jam yang lalu',
    windowHours: 36,
    thumbnail: 'https://picsum.photos/seed/sandal-slide/400/300',
    competitorCount: 56,
    avgPrice: 78000,
    reviewVelocity: 102,
    description: 'Sandal slide dengan sole empuk dan look premium. Musim panas memicu demand tinggi.',
    recommendation: 'Pertimbangkan ulang — kompetisi meningkat. Bedakan dengan warna atau material unik.',
  },
  {
    id: '12',
    name: 'Charger Magnetic 3in1',
    category: 'elektronik',
    growth: 213,
    saturation: 33,
    phase: 'Growing',
    platform: 'TikTok Shop',
    timeDetected: '1 jam yang lalu',
    windowHours: 62,
    thumbnail: 'https://picsum.photos/seed/charger-magnetic/400/300',
    competitorCount: 19,
    avgPrice: 145000,
    reviewVelocity: 203,
    description: 'Charger wireless magnetic 3in1 untuk iPhone, Watch, dan AirPods. Viral di unboxing TikTok.',
    recommendation: 'Aman masuk — peluang terbuka. Stok 40 pcs dengan modal Rp 3 juta.',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    trendId: '2',
    trendName: 'Lampu Tidur 3D Moon',
    urgency: 'Critical',
    windowHours: 68,
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    read: false,
  },
  {
    id: 'n2',
    trendId: '12',
    trendName: 'Charger Magnetic 3in1',
    urgency: 'High',
    windowHours: 62,
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    read: false,
  },
  {
    id: 'n3',
    trendId: '1',
    trendName: 'Botol Minum Kaca Viral',
    urgency: 'High',
    windowHours: 58,
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    read: false,
  },
  {
    id: 'n4',
    trendId: '3',
    trendName: 'Tisu Basah Portable',
    urgency: 'Medium',
    windowHours: 18,
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    read: true,
  },
  {
    id: 'n5',
    trendId: '4',
    trendName: 'Lampu Proyektor Aurora',
    urgency: 'High',
    windowHours: 52,
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    read: true,
  },
  {
    id: 'n6',
    trendId: '7',
    trendName: 'Tote Bag Kanvas Custom',
    urgency: 'Medium',
    windowHours: 44,
    timestamp: new Date(Date.now() - 28 * 3600000).toISOString(),
    read: true,
  },
];

export const categories = [
  { id: 'all', label: 'Semua' },
  { id: 'fashion', label: 'Fashion' },
  { id: 'elektronik', label: 'Elektronik' },
  { id: 'rumah-tangga', label: 'Rumah Tangga' },
  { id: 'kecantikan', label: 'Kecantikan' },
  { id: 'makanan', label: 'Makanan' },
];

export const sortOptions = [
  { id: 'window', label: 'Window Tersisa' },
  { id: 'saturation', label: 'Saturation Terendah' },
  { id: 'growth', label: 'Growth Tertinggi' },
];

const mockVideoUrl = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';

export const mockContentData: ContentItem[] = [
  {
    id: 'c1',
    title: 'Botol Minum Kaca Viral - Unboxing & Review',
    creator: '@dapurminimalis',
    platform: 'TikTok',
    views: '2.4M',
    engagement: '8.5%',
    likes: '145K',
    comments: '3.2K',
    thumbnail: 'https://picsum.photos/seed/botol-minum/400/600',
    productRelevance: true,
    duration: '0:45',
    url: 'https://www.tiktok.com',
    videoUrl: mockVideoUrl,
  },
  {
    id: 'c2',
    title: 'DIY Lampu Tidur 3D - Tutorial Lengkap',
    creator: '@homedecorid',
    platform: 'TikTok',
    views: '1.8M',
    engagement: '12.3%',
    likes: '98K',
    comments: '5.1K',
    thumbnail: 'https://picsum.photos/seed/lampu-moon/400/600',
    productRelevance: true,
    duration: '1:20',
    url: 'https://www.tiktok.com',
    videoUrl: mockVideoUrl,
  },
  {
    id: 'c3',
    title: 'Morning Routine dengan Tote Bag Custom',
    creator: '@lifestylejkt',
    platform: 'Instagram',
    views: '890K',
    engagement: '6.7%',
    likes: '67K',
    comments: '1.8K',
    thumbnail: 'https://picsum.photos/seed/tote-bag/400/600',
    productRelevance: true,
    duration: '0:30',
    url: 'https://www.instagram.com',
    videoUrl: mockVideoUrl,
  },
  {
    id: 'c4',
    title: 'Skincare Routine - Serum Niacinamide',
    creator: '@skincareaddict.id',
    platform: 'Instagram',
    views: '3.1M',
    engagement: '9.2%',
    likes: '234K',
    comments: '8.7K',
    thumbnail: 'https://picsum.photos/seed/serum-niacinamide/400/600',
    productRelevance: true,
    duration: '0:55',
    url: 'https://www.instagram.com',
    videoUrl: mockVideoUrl,
  },
  {
    id: 'c5',
    title: 'Unboxing Charger Magnetic 3in1',
    creator: '@techreview.id',
    platform: 'TikTok',
    views: '5.2M',
    engagement: '15.1%',
    likes: '412K',
    comments: '12.3K',
    thumbnail: 'https://picsum.photos/seed/charger-magnetic/400/600',
    productRelevance: true,
    duration: '0:38',
    url: 'https://www.tiktok.com',
    videoUrl: mockVideoUrl,
  },
  {
    id: 'c6',
    title: 'Smartwatch Anak - Review Fitur GPS',
    creator: '@parentingtech',
    platform: 'TikTok',
    views: '1.5M',
    engagement: '7.8%',
    likes: '89K',
    comments: '4.5K',
    thumbnail: 'https://picsum.photos/seed/smartwatch-anak/400/600',
    productRelevance: true,
    duration: '2:10',
    url: 'https://www.tiktok.com',
    videoUrl: mockVideoUrl,
  },
];
